import { useQuery } from "@tanstack/react-query";
import { api } from "../api";
import { ErrorState, LoadingState } from "../components/StatePanel";
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
export function ModelInfoPage() {
  const query = useQuery({ queryKey: ["model-info"], queryFn: api.modelInfo });
  const learningQuery = useQuery({ queryKey: ["learning-status"], queryFn: api.learningStatus });
  if (query.isLoading) return <LoadingState label="Loading model information" />;
  if (query.error || !query.data) return <ErrorState message={query.error?.message ?? "Model metadata is unavailable."} retry={() => void query.refetch()} />;
  const model = query.data;
  return <section><div className="page-heading"><div><p className="eyebrow">Transparency & governance</p><h1>Model information</h1><p>Runtime versions, policy configuration, and evaluation evidence.</p></div><span className="ready-pill"><i />{model.status ?? "Ready"}</span></div>
    <div className="model-grid"><article className="card model-hero"><span className="model-icon" aria-hidden="true">◎</span><div><p className="eyebrow">Selected classifier</p><h2>{model.model_name ?? "Fraud classifier"}</h2><p>Bundle {model.bundle_id ?? model.model_version}</p></div></article>
      <article className="card"><div className="card-heading"><h2>Runtime contract</h2><p>Immutable artifact identifiers</p></div><dl className="info-list"><div><dt>Model version</dt><dd>{model.model_version}</dd></div><div><dt>Risk config</dt><dd>{model.risk_config_version ?? "See runtime bundle"}</dd></div><div><dt>Feature schema</dt><dd>{model.feature_schema_version}</dd></div></dl></article>
      <article className="card"><div className="card-heading"><h2>Decision thresholds</h2><p>Configurable policy boundaries</p></div>{model.thresholds ? <div className="threshold-scale"><div className="scale-bar"><span /><span /><span /></div><div className="scale-labels"><span>0<br/><small>Approve</small></span><span>{model.thresholds.manual_review}<br/><small>Review</small></span><span>{model.thresholds.high_risk}<br/><small>High risk</small></span><span>100</span></div></div> : model.classifier_threshold !== undefined ? <div className="single-stat"><strong>{model.classifier_threshold.toFixed(3)}</strong><span>Classifier operating threshold</span></div> : <p className="muted">Threshold metadata is not exposed by this bundle.</p>}</article>
      <article className="card"><div className="card-heading"><h2>Hybrid weights</h2><p>How component scores are combined</p></div>{model.weights && Object.keys(model.weights).length ? <div className="weight-list">{Object.entries(model.weights).map(([key, value]) => <div key={key}><span>{pretty(key)}</span><strong>{Math.round(value * 100)}%</strong></div>)}</div> : <p className="muted">Weight metadata is retained by the risk policy but not exposed by this endpoint.</p>}</article>
      <article className="card metrics-card"><div className="card-heading"><h2>Held-out metrics</h2><p>Evaluation evidence packaged with the selected model</p></div>{model.metrics && Object.keys(model.metrics).length ? <div className="metric-grid">{Object.entries(model.metrics).map(([key, value]) => <div key={key}><span>{pretty(key)}</span><strong>{value === null ? "N/A" : value.toFixed(3)}</strong></div>)}</div> : <p className="muted">Evaluation metrics are not exposed by this bundle.</p>}</article>
      <article className="card learning-card"><div className="card-heading"><h2>Governed learning loop</h2><p>Verified investigator outcomes, not unreviewed predictions</p></div>{learningQuery.data ? <><div className="metric-grid"><div><span>Reviewed</span><strong>{learningQuery.data.reviewed_applications}/{learningQuery.data.minimum_feedback_required}</strong></div><div><span>False-positive reviews</span><strong>{Math.round(learningQuery.data.false_positive_review_rate * 100)}%</strong></div><div><span>Missed fraud</span><strong>{learningQuery.data.missed_fraud_reviews}</strong></div></div><p className={`learning-status ${learningQuery.data.retraining_recommended ? "attention" : ""}`}>{pretty(learningQuery.data.governance_status)}</p></> : <p className="muted">{learningQuery.error ? "Learning indicators are unavailable." : "Loading feedback evidence…"}</p>}<p className="governance-copy">Retraining is recommended only after enough reviewed evidence, then requires validation and human approval before a new immutable model is deployed.</p></article>
      <article className="card features-card"><div className="card-heading"><h2>Feature contract</h2><p>{model.features?.length ?? 0} validated, ordered model inputs</p></div>{model.features?.length ? <ul className="feature-list">{model.features.map(feature => { const name = typeof feature === "string" ? feature : feature.name; const description = typeof feature === "string" ? undefined : feature.description; return <li key={name}><strong>{pretty(name)}</strong>{description && <span>{description}</span>}</li>; })}</ul> : <p className="muted">Feature names are governed by schema {model.feature_schema_version}.</p>}</article>
      <article className="responsible-note"><strong>Prototype decision support</strong><p>Metrics on synthetic or benchmark data do not establish production fitness or fairness. Human review protects applicants from automated false positives; sensitive characteristics are intentionally excluded.</p></article>
    </div>
  </section>;
}
